# Site Settings
title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  A simple guide to get started with jekyll.
baseurl: "/testjekyll" # the subpath of your site, e.g. /blog
url: "http://namrajp.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: wouraj
github_username: namrajp

# Build settings
sass:
  sass_dir: _sass
include: ["_pages"]
kramdown:
  input: GFM

theme: jekyll-theme-minimal